CREATE TABLE IF NOT EXISTS proxy (
    id SERIAL PRIMARY KEY,
    ip VARCHAR(15) NOT NULL,
    port INTEGER NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    status BOOLEAN DEFAULT TRUE NOT NULL,
    request INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
)
